<?php
// 印出字串
echo "Hello, PHP!";
echo "<h2>Hello, PHP!</h2>";
$number = 5;
$number=$number+10;
echo $number;
echo "<br>";
$name = "Harry Potter";
$age = 18;
//用.做字串相連
echo "<br>我的名字".$name."<br>";
echo "<br>";
echo "我的年齡".$age."<br>";
$a = "1";
$b = 1;
$c = $a.$b;
$d = $a+$b;
echo "a=".$a."<br>";
echo "b=".$b."<br>";
echo "c=".$c."<br>";
echo "d=".$d."<br>";
echo '$a'."的型態：".gettype($a)."<br>";
echo '$b'."的型態：".gettype($b)."<br>";
echo '$c'."是".$c."<br>";
echo '$d'."是".$d."<br>";
var_dump($a);
echo "<br>";
var_dump($b);
echo "<br>";
var_dump($c);
echo "<br>";
var_dump($d);
echo "<br>";
echo 'I\'m happy!';
echo "<br>";
define("PI",3.14159);
echo PI;
echo "<br>";
define("USERNAME","sue");
echo USERNAME;
echo "<br>";
$x = 5;
$y = 2;
echo "5除於2的餘數是:".$x%$y;
echo "<br>";
$q =1;
echo '$q++ --> '. $q++."<br>";
echo $q."<br>";
$w =1;
echo '++$w --> '. ++$w."<br>";
echo $w."<br>";
$score_Ch = 70;
$score_En = 65;
$score_Math = 80;
$sum = $score_Ch+$score_En+$score_Math;
// 指定小數位數到第幾位
$avg = round($sum/3,2);
echo "國文成績：".$score_Ch."分<br>";
echo "英文成績：".$score_En."分<br>";
echo "數學成績：".$score_Math."分<br>";
echo "總分為：".$sum."分<br>";
echo "平均為：".$avg."分<br>";
$t=1;
$y="1";
var_dump($t==$y);
echo "<br>";
var_dump($t===$y);
echo "<br>";
?>